### ISSUE TITLE
能否支持ipv6？

### ISSUE THREAD

**Issue by DragonFSKY** [CokeMine/ServerStatus-Hotaru#10]
有台纯ipv6的服务器 发现用服务端的ipv6地址连接不上

**Comment by CokeMine** [comment]
Hi,
请使用我更新后的clients/status-client_ipv6.py 替换掉原来的status-client.py
配置时ip处不需要加方括号。

**Comment by DragonFSKY** [comment]
是在客户端修改吗,我在客户端修改后是这样配置的
  ServerStatus 客户端配置信息：
 
  IP 	: 2a03:5a00:1:4:1000::1c8
  端口 	: 35601
  账号 	: servarica
  密码 	: doub.io
 
————————————————————
不过还是不行,不知道是不是ipv6网的问题

**Comment by CokeMine** [comment]
> 多谢大佬,是在客户端修改吗,我现在客户端修改后是这样配置的
> ServerStatus 客户端配置信息：
> 
> IP : 2a03:5a00:1:4:1000::1c8
> 端口 : 35601
> 账号 : servarica
> 密码 : doub.io
> 
> ————————————————————
> 不过还是不行,不知道是不是ipv6网的问题

把客户端/usr/local/ServerStatus/client/status-client.py更换为https://github.com/CokeMine/ServerStatus-Hotaru/blob/master/clients/status-client_ipv6.py
重命名为status-client.py替换掉 然后在客户端的脚本中进行修改配置信息

已在Vultr 日本测试通过

如果还不行的话，你把IPV6的简写换成全写试试？
