### ISSUE TITLE
service会在manjaro上错误的杀死进程

### ISSUE THREAD

**Issue by MasterOfStar** [cokemine/ServerStatus-Hotaru#100]
manjaro系统下，systemd下的service会错误的杀死进程
![image](https://user-images.githubusercontent.com/21274896/129231213-e80e2bfe-3a13-4464-a2c1-c1edd9a8afeb.png)

直接通过python运行py 或/etc/init.d/statusclient start运行则不会错误的退出

**Comment by cokemine** [comment]
试试新的`service`?

**Comment by MasterOfStar** [comment]
> 试试新的`service`?

现在ok了
