### ISSUE TITLE
客户端一直出现list index out of range错误，无法正常连接到服务端

### ISSUE THREAD

**Issue by MAX-XiaoKui** [cokemine/ServerStatus-Hotaru#103]
客户端报错：
````
You are connecting via: IPv4

('Caught Exception:', IndexError('list index out of range',))
Connecting...
Authentication successful. Access granted.
````
和服务端相连的其他服务端没有这个问题
尝试过重装客户端、重启系统
系统是Debian 10，和服务端连的其他系统也都是Debian 10
网页上一直在这两个状态之间跳：
![image](https://user-images.githubusercontent.com/53287753/130222769-35987d2f-ef7d-4547-9d24-83b87e687c07.png)
![image](https://user-images.githubusercontent.com/53287753/130222817-91a4b715-2a88-4ce9-888c-576f85e2e6b9.png)

**Comment by cokemine** [comment]
是使用了vnStat吗？

**Comment by MAX-XiaoKui** [comment]
对

**Comment by cokemine** [comment]
> 对

参考这里 https://github.com/cokemine/ServerStatus-Hotaru/issues/94#issuecomment-882340427

我会加个判断在vnStat收集数据时候不报错。

如果长时间list index out of range 可能是 vnStat 没有安装成功

**Comment by MAX-XiaoKui** [comment]
好了，手动安装vnStat然后重装客户端就好了

**Comment by MAX-XiaoKui** [comment]
谢谢
