### ISSUE TITLE
配置config.js錯誤

### ISSUE THREAD

**Issue by Naruse-developer** [cokemine/ServerStatus-Hotaru#108]
input --> header:_'<img src="./log.png" alt="log">_'

output _<img src="./log.png" alt="log">_

我想把标题换成图片，结果输出html的文字

**Comment by Naruse-developer** [comment]
![image](https://user-images.githubusercontent.com/32754492/132490279-ab6aaebb-ac28-4686-915d-b90c0ccf82f4.png)

**Comment by Naruse-developer** [comment]
![image](https://user-images.githubusercontent.com/32754492/132490333-584c7177-d56c-4110-9eb7-90a44cf2281c.png)

**Comment by cokemine** [comment]
这个是因为 Vue 的安全限制。要是想改成图片只能手动把https://github.com/cokemine/hotaru_theme/blob/3575212be2c1e1016dfd4aeef98878538524595f/src/components/TheHeader.vue#L5 改掉然后重新打包了

**Comment by Naruse-developer** [comment]
好了我直接改css就行了
