### ISSUE TITLE
Caddy 启动失败 !

### ISSUE THREAD

**Issue by yesepa** [cokemine/ServerStatus-Hotaru#110]
发现 Caddy 配置文件非空，开始追加 ServerStatus 网站配置内容到文件最后...

这该怎么解决》求教

**Comment by yesepa** [comment]
http://xxx.com:80 {
  root * /usr/local/ServerStatus/web
  encode gzip
  file_server
}

**Comment by cokemine** [comment]
`cat /tmp/caddy.log`

**Comment by yesepa** [comment]
{"level":"info","ts":1634789288.547153,"msg":"using provided configuration","config_file":"/usr/local/caddy/Caddyfile","config_adapter":""}
{"level":"info","ts":1634789288.548829,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1634789288.5490112,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
run: loading initial config: loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: address already in use

**Comment by cokemine** [comment]
80端口被占用了。
应该是你的VPS本来就有一个Web服务器、Nginx、Apache之类的
