### ISSUE TITLE
Rocky Linux 8 安装客户端时无法编译安装vnStat

### ISSUE THREAD

**Issue by misakano2975** [cokemine/ServerStatus-Hotaru#116]
![image.png](https://s2.loli.net/2021/12/18/da27h8YXLR6TGDs.png)

**Comment by cokemine** [comment]
@misakano2975 手动运行一下 `yum -y groupinstall "Development Tools"` 试试

**Comment by misakano2975** [comment]
> yum -y groupinstall "Development Tools"

可以了，建议把这段加到一键脚本上面
