### ISSUE TITLE
取消系统升级

### ISSUE THREAD

**Issue by skoy03** [cokemine/ServerStatus-Hotaru#119]
能否去掉系统升级呢？我这系统有点奇葩，升级了系统更换了内核，会死机

**Comment by cokemine** [comment]
Debian `apt update`不会更新内核。
CentOS 或者 ArchLinux 用户可以修改源更新时锁定内核

**Comment by skoy03** [comment]
不会锁定呢

> Debian`apt update`不会更新内核。 COS 或者 ArchLinux 可以修改源更新时锁定核心用户

**Comment by cokemine** [comment]
这需要你自行修改源去设置

**Comment by myxuchangbin** [comment]
这个`yum update`确实挺闹心的，如果只是和`apt update`达到一样的效果，更新源缓存而已
那么我认为修改为：`yum clean all && yum makecacke`更加合适
一来可以大大减少安装时间，二来可以避免一些因升级带来的问题

**Comment by myxuchangbin** [comment]
@cokemine 大佬是否考虑做一下修改
