### ISSUE TITLE
安装过bbr plus 后无法编译serverstats服务端

### ISSUE THREAD

**Issue by 631894570** [CokeMine/ServerStatus-Hotaru#12]
gcc -c -Iinclude -Wall -O2 src/system.c -o obj/system.o
In file included from /usr/include/sys/socket.h:39:0,
                 from src/system.c:19:
/usr/include/bits/socket.h:346:24: 致命错误：asm/socket.h：没有那个文件或目录
 #include <asm/socket.h>
                        ^
编译中断。
make: *** [obj/system.o] 错误 1
[错误] ServerStatus 服务端编译失败 !

**Comment by CokeMine** [comment]
1.你用的什么系统。我在Debian9 4.14.129内核安装BBRPLUS后是能编译Serverstatus成功的。
2.你有试过不安装BBRPlus然后安装Serverstatus看看能不能成功？

**Comment by 631894570** [comment]
CENTOS7  应该是DD源的问题  已经重装Debian9解决
