### ISSUE TITLE
issue:这个前端界面支持加入账号和密码才能 访问吗？

### ISSUE THREAD

**Issue by dcdebug** [cokemine/ServerStatus-Hotaru#128]
这个前端界面支持加入账号和密码才能 访问吗？
我想让这个监控只让有账号的同事访问，请问这个支持吗？有比较好的解决方案吗？或者第三方插件推荐？
Thanks..麻烦了，占用了您的时间..

**Comment by cokemine** [comment]
Caddy 支持 Basic Auth https://caddyserver.com/docs/caddyfile/directives/basicauth
应该可以达到类似的效果

**Comment by dcdebug** [comment]
Thanks ,I use the Nginx support the function.
https://www.onlycsg.com/archives/790.html
