### ISSUE TITLE
有前端css的本地备份嘛

### ISSUE THREAD

**Issue by thisyounguncle** [cokemine/ServerStatus-Hotaru#132]
https://cdn.jsdelivr.net/npm/semantic-ui/dist/semantic.min.css   前端的css找不到了

**Comment by cokemine** [comment]
jsdelivr 估计不会恢复了
先本地化吧。

**Comment by thisyounguncle** [comment]
您有文件嘛，可以发我一下吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月21日 13:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [cokemine/ServerStatus-Hotaru] 有前端css的本地备份嘛 (Issue #132) |

jsdelivr 估计不会恢复了
先本地化吧。

**Comment by cokemine** [comment]
@thisyounguncle https://github.com/cokemine/hotaru_theme/releases/tag/v0.4.4 最新的 release 已经把静态资源本地化了

可以直接替换现有的前端

https://github.com/cokemine/ServerStatus-Hotaru#%E6%9B%B4%E6%96%B0%E5%89%8D%E7%AB%AF

**Comment by thisyounguncle** [comment]
好的，谢谢
