### ISSUE TITLE
caddy安装失败

### ISSUE THREAD

**Issue by look6657** [cokemine/ServerStatus-Hotaru#134]
换了好多台机子，caddy老是安装失败，请更新脚本，谢谢！

**Comment by cokemine** [comment]
什么系统
以及指令集

**Comment by look6657** [comment]
debian11，x86

**Comment by look6657** [comment]
W: GPG error: https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABA1F9B8875A6661
E: The repository 'https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
[错误] Caddy安装失败，请手动部署，Web网页文件位置：/usr/local/ServerStatus/web



换了好几台vps安装，都是报错以上信息
