### ISSUE TITLE
服务端突然启动不起来了

### ISSUE THREAD

**Issue by huangsiyuan924** [cokemine/ServerStatus-Hotaru#137]
在添加一个客户端节点后，突然就服务端挂掉了，无法启动，服务端的功能都报错parse error: Invalid literal at line 16, column 24
parse error: Invalid literal at line 16, column 24

**Comment by huangsiyuan924** [comment]
重新安装了下服务端，可以启动了

**Comment by cokemine** [comment]
估计是节点名添加了一些特殊字符导致 jq 无法正常处理 json 了
https://github.com/cokemine/ServerStatus-Hotaru/issues/114

**Comment by huangsiyuan924** [comment]
> 估计是节点名添加了一些特殊字符导致 jq 无法正常处理 json 了 #114

好了谢谢
