### ISSUE TITLE
这个怎么说？

### ISSUE THREAD

**Issue by CitrusFlavored** [cokemine/ServerStatus-Hotaru#152]
![image](https://github.com/cokemine/ServerStatus-Hotaru/assets/54226117/72396f54-d58e-48cf-8008-c47e65788e3a)
![image](https://github.com/cokemine/ServerStatus-Hotaru/assets/54226117/14eab15b-a77f-430e-96a5-6759ad738088)
![image](https://github.com/cokemine/ServerStatus-Hotaru/assets/54226117/317b2dfb-92c8-4237-acfa-c05c21b73215)

这是包含恶意程序？联系多个ip的13333端口

**Comment by cokemine** [comment]
截图具体是什么进程在和13333端口通信

**Comment by CitrusFlavored** [comment]
> 

不知'我找了好久找不到'但是是安装该探针后出现的，停止该探针后就不再出现

**Comment by CitrusFlavored** [comment]
> 截图具体是什么进程在和13333端口通信

不知'我找了好久找不到'但是是安装该探针后出现的，停止该探针后就不再出现

**Comment by cokemine** [comment]
客户端还是服务端？

**Comment by CitrusFlavored** [comment]
> 客户端还是服务端？

客户端服务端均有，服务端较多，客户端一天几条

**Comment by CitrusFlavored** [comment]
> 



> 客户端还是服务端？

以上截图使用以下命令监听得到：tcpdump -i eth0 port 13333

**Comment by CitrusFlavored** [comment]
> 客户端还是服务端？



> > 
> 
> > 客户端还是服务端？
> 
> 以上截图使用以下命令监听得到：tcpdump -i eth0 port 13333

不是启动后立马出现，启动探针服务后使用命令监听，几个小时内会出现，关闭服务后不再出现（已四合院screen监听一整天都没出现）

**Comment by CitrusFlavored** [comment]
close

**Comment by CitrusFlavored** [comment]
close
