### ISSUE TITLE
未来有计划会添加Dark Mod吗？

### ISSUE THREAD

**Issue by SneakyTurt1e** [CokeMine/ServerStatus-Hotaru#18]
其实现在也挺好，如果作者有余力为该探针添加暗黑模式，在夜晚看起来就不会那么刺眼啦。

**Comment by CokeMine** [comment]
@SneakyTurt1e 
Hi,
我尝试添加了Darkmode，可以通过更换Web前端文件直接更新前端
样式可能不尽如人意，各位有更好的样式或实现方法欢迎提交PR
