### ISSUE TITLE
有对mips的支持吗？

### ISSUE THREAD

**Issue by MasterOfStar** [CokeMine/ServerStatus-Hotaru#19]
路由器运行提示status.sh: line 437: syntax error: bad for loop variable

**Comment by 780112753** [comment]
同求对mips的支持   Pandavan安装提示syntax error: bad for loop variable

**Comment by CokeMine** [comment]
客户端建议用opkg自行安装python3尝试手动运行客户端
服务端不建议放到路由器了，性能吃不下
由于本人没有很好的测试平台设备，没办法测试抱歉
