### ISSUE TITLE
如何设置探针不统计docker内网的流量

### ISSUE THREAD

**Issue by SilentFlower** [CokeMine/ServerStatus-Hotaru#23]
图为接口实际流量
[![19696de83a89d9a74d7d200ee746c9b3.jpg](https://cdn2.hemacdn.com/img/19696de83a89d9a74d7d200ee746c9b3.jpg)](https://img.wang/image/3cvtK)

图为探针显示的流量
[![c92721c71662488bafd0baf7d3446893.jpg](https://cdn2.hemacdn.com/img/c92721c71662488bafd0baf7d3446893.jpg)](https://img.wang/image/3chW7)

请问如何设置才能不统计dokcer内网的流量

**Comment by SilentFlower** [comment]
没事了已经解决

**Comment by laogui2008** [comment]
今天遇到同样问题，写下自己的解决方法，以后有碰到同样问题的朋友，可参考下

修改方法：修改status-client.py文件的代码，具体代码在类Traffic的get方法中，将不需要统计流量的网卡接口排除即可

根据status.sh可知，status-client.py文件在/usr/local/ServerStatus/client目录下

先用 `cat /proc/net/dev` 命令查看网卡有哪些，我的是：lo、eth0、docker0、br-1bfaa12c35f1、vethf0edf50、veth9b7a34d
实际上，我只需要统计eth0的流量，其他都不要，在代码中排除即可

将原代码 
`if dev[0].strip() == "lo" or dev[0].find("tun") > -1` 
改成 
`if dev[0].strip() == "lo" or dev[0].strip() == "docker0" or dev[0].find("br-") > -1 or dev[0].find("veth") > -1 or dev[0].find("tun") > -1`

最后用 `bash status.sh c` 命令重启客户端

**Comment by CokeMine** [comment]
@laogui2008 谢谢，这个issue打开后直接关闭了。我没有看到这个issue，如果使用vnStat计算流量的话应该不会存在这个问题，因为是指定网口的。或许我们把流量计算默认直接排除掉docker的流量比较好？

**Comment by laogui2008** [comment]
@CokeMine 一般来说，大部分人在使用过程中应该是很少关注docker内网的流量使用情况的，更多的是关注对外的流量使用情况。理论上，为了适应大部分人的使用习惯，是应该排除掉docker内网的流量比较好。但使用docker虚拟出来的网卡，不同的机子得到的可能是不一样的，排除起来可能有一些困难。该怎么排除，需要考虑考虑。
事实上，可能同时使用docker和探针的人比较少，所以提出相关issue不多。
如果真要做，就要辛苦大佬你了。

**Comment by CokeMine** [comment]
fix in https://github.com/CokeMine/ServerStatus-Hotaru/commit/56b55874f0cb7214bfab73c858cd106ca140dff9
