### ISSUE TITLE
Windows支持

### ISSUE THREAD

**Issue by USS-LongIsland** [CokeMine/ServerStatus-Hotaru#26]
emmm咱想着在Windows上面跑py 结果发现没法读数据

**Comment by CokeMine** [comment]
Hi,

我这里push了一份tenyue的老版本，可能对流量有些问题，以后再修改。

<https://raw.githubusercontent.com/CokeMine/ServerStatus-Hotaru/master/clients/status-psutil.py>

Windows安装Python2.7，修改status-psutil.py配置文件

## 安装pip

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
C:\Python27\python.exe get-pip.py
```

## 安装psutil

```
C:\Python27\python.exe -m pip install psutil
```

## 运行Serverstatus

```
C:\Python27\python.exe status-psutil.py
```

**Comment by USS-LongIsland** [comment]
感谢w 另外祝节日快乐
