### ISSUE TITLE
服务端只能显示本机负载情况，无法接受其他客户端负载信息

### ISSUE THREAD

**Issue by misakamisaka10086** [CokeMine/ServerStatus-Hotaru#27]
服务端内核python版本2.7.5，centos 7内核3.10.0-1062.18.1.el7.x86_64

**Comment by misakamisaka10086** [comment]
> 
> 
> 服务端python版本2.7.5，centos 7内核3.10.0-1062.18.1.el7.x86_64
客户端python版本2.75，centos 7 内核5.7.9-1.el7.elrepo.x86_64
都已关闭防火墙，serverstatus显示启动成功，但是负载状态: undefined%，

**Comment by CokeMine** [comment]
Hi,
请问是只有负载不能正常显示吗，内存之类的都可以？

**Comment by CokeMine** [comment]
Hi,
@misakamisaka10086 
我刚刚测试了一下
目前来看估计5内核就会出现这种情况，详见issue #11 
原因未知（我啥都不会），不过目前暂时的解决方法就是注释掉169行的data = s.recv(1024)，然后重启客户端
https://github.com/CokeMine/ServerStatus-Hotaru/blob/1ec64f6c4937b5ef2073c2d6164197be7ddc5df3/clients/status-client.py#L169

**Comment by misakamisaka10086** [comment]
> 嗨，
> @ misakamisaka10086
> 我刚刚测试了一下
> 目前来看估计5内核就会出现这种情况，详见issue [＃11](https://github.com/CokeMine/ServerStatus-Hotaru/issues/11)
> 原因未知（我啥都不会），不过目前暂时的解决方法就是注释掉169行的数据= s.recv（1024），然后重启客户端
> https://github.com/CokeMine/ServerStatus-Hotaru/blob/1ec64f6c4937b5ef2073c2d6164197be7ddc5df3/clients/status-client.py#L169

您好，非常感谢您的回复，目前已通过更新客户端解决此问题，谢谢ღ( ´･ᴗ･` )比心
