### ISSUE TITLE
貌似不支持IPV6

### ISSUE THREAD

**Issue by BlueSkyXN** [CokeMine/ServerStatus-Hotaru#29]
在启动了V6的机子上好像无法读取数据

**Comment by CokeMine** [comment]
Hi,是纯ipv6吗

**Comment by BlueSkyXN** [comment]
> @BlueSkyXN嗨，是纯ipv6吗

V4V6都有，试了下开V6无法读取本地status，但是可以读取其他机器的，很奇怪

**Comment by CokeMine** [comment]
@BlueSkyXN  也就是说装有服务端的客户端填写127.0.0.1无法获取数据？什么系统和Linux内核版本？

**Comment by BlueSkyXN** [comment]
> @BlueSkyXN初始化 内置服务端的客户端填充127.0.0.1无法获取数据？什么系统和Linux内核版本？

还能直接填IP的吗，我都是填域名，我试试127.0.0.1

**Comment by BlueSkyXN** [comment]
> @BlueSkyXN重置 内置服务端的客户端填充127.0.0.1无法获取数据？什么系统和Linux内核版本？

还是一样，不行，读取不到，CentOS 7.8.2003(Py3.7.8)，5.5.0，BBR

德国Contabo，宝塔企业版

**Comment by BlueSkyXN** [comment]
我也不清楚是v6还是其他的问题，有其他依赖要求？权限要求？

**Comment by BlueSkyXN** [comment]
卸载的时候还出现了奇怪的报错
https://ae01.alicdn.com/kf/Ud4fe2cbfb1f04cb2b83fb1d983728ef4z.jpg

**Comment by CokeMine** [comment]
@BlueSkyXN 默认python -V是多少？
5内核环境下ServerStatus确实有些问题，解决方法见 #11 #27

**Comment by BlueSkyXN** [comment]
> @BlueSkyXN默认蟒蛇-V是多少？
> 5内核环境下ServerStatus确实有些问题，解决方法见[＃11 ](https://github.com/CokeMine/ServerStatus-Hotaru/issues/11) [＃27](https://github.com/CokeMine/ServerStatus-Hotaru/issues/27)

[root@SKY ~]# python -V
Python 2.7.5
[root@SKY ~]# python3 -V
Python 3.6.8

默认走py2的问题?

**Comment by CokeMine** [comment]
把169行的data = s.recv(1024)注释掉吧
https://github.com/CokeMine/ServerStatus-Hotaru/issues/27#issuecomment-663858497

**Comment by BlueSkyXN** [comment]
> 把169行的数据= s.recv（1024）注掉吧
> [＃27（评论）](https://github.com/CokeMine/ServerStatus-Hotaru/issues/27#issuecomment-663858497)

仍然无效
使用其他服务器作为服务端，也无法读取这台机器的数据，是不是监测的client有问题

**Comment by CokeMine** [comment]
> > 把169行的数据= s.recv（1024）注掉吧
> > [＃27（评论）](https://github.com/CokeMine/ServerStatus-Hotaru/issues/27#issuecomment-663858497)
> 
> 仍然无效
> 使用其他服务器作为服务端，也无法读取这台机器的数据，是不是监测的client有问题

@BlueSkyXN 尝试通过脚本更新一下客户端，若还是不行，请再次注释/usr/local/ServerStatus/client/status-client.py 169行的data = s.recv(1024)，然后重启一下客户端。
在新内核+BBR的环境可能会出现粘包问题
