### ISSUE TITLE
Caddy 解压失败或压缩文件错误 !

### ISSUE THREAD

**Issue by DocWho22** [CokeMine/ServerStatus-Hotaru#30]
Location: https://github.com/caddyserver/caddy/releases/download/v2.1.1/caddy__linux_amd64.tar.gz [following]
--2020-08-02 02:44:59--  https://github.com/caddyserver/caddy/releases/download/v2.1.1/caddy__linux_amd64.tar.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-08-02 02:44:59 ERROR 404: Not Found

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[错误] Caddy 解压失败或压缩文件错误 !
[错误] Caddy安装失败，请手动部署，Web网页文件位置：

**Comment by DocWho22** [comment]
caddy最新地址应该是https://github.com/caddyserver/caddy/releases/download/v2.1.1/caddy_2.1.1_linux_amd64.tar.gz
但是脚本会对https://github.com/caddyserver/caddy/releases/download/v2.1.1/caddy__linux_amd64.tar.gz

**Comment by DocWho22** [comment]
latest_ver似乎是空的

**Comment by CokeMine** [comment]
@DocWho22 是不是没有装curl.....

**Comment by DocWho22** [comment]
> @DocWho22 是不是没有装curl.....

谢谢==
确实是这个原因。刚dd完系统。麻烦了！
