### ISSUE TITLE
提个意见

### ISSUE THREAD

**Issue by NiuXZi** [CokeMine/ServerStatus-Hotaru#31]
可以统计下总共用了多少流量吗，重启一下流量就清零了好难受啊。

**Comment by ColderCoder** [comment]
请问流量统计是否是每月重置，可否加入每月几号重置的设定？

**Comment by CokeMine** [comment]
> 请问流量统计是否是每月重置，可否加入每月几号重置的设定？

@ColderCoder 一般是通过vnStat实现，但是vnStat好像每月这个功能

**Comment by CokeMine** [comment]
@NiuXZi @ColderCoder 这边尝试添加了vnStat每月流量统计功能，可以设置每月某一号重置流量。期待反馈

**Comment by ColderCoder** [comment]
在Debian 10 x86_64 (KVM) 正常运作
