### ISSUE TITLE
客户端是否支持MacOS系统

### ISSUE THREAD

**Issue by LexBurner97** [CokeMine/ServerStatus-Hotaru#32]
下载和配置客户端时出现以下错误，觉得是脚本不支持MacOS

status.sh: line 938: iptables: command not found
status.sh: line 939: iptables: command not found
sed: 1: "/usr/local/ServerStatus ...": extra characters at the end of l command
sed: 1: "/usr/local/ServerStatus ...": extra characters at the end of l command
sed: 1: "/usr/local/ServerStatus ...": extra characters at the end of l command
sed: 1: "/usr/local/ServerStatus ...": extra characters at the end of l command
status.sh: line 933: iptables: command not found
status.sh: line 934: iptables: command not found
status.sh: line 878: /etc/init.d/status-client: No such file or directory

**Comment by CokeMine** [comment]
@LexBurner97 Hey，手动运行客户端哦

**Comment by LexBurner97** [comment]
好的，最终还是搭建在了云服务器，本地安装服务器比较麻烦一些，谢谢了
