### ISSUE TITLE
更改网址默认端口

### ISSUE THREAD

**Issue by LexBurner97** [CokeMine/ServerStatus-Hotaru#33]
最初安装客户端的时候直接回车了想更改一下端口，请问一下大佬存放端口的文件在哪里？谢谢

**Comment by CokeMine** [comment]
@LexBurner97 Hi
请问你要更新客户端端口还是服务端的监听端口（35601）
还是网站前端的默认端口？

**Comment by LexBurner97** [comment]
> @LexBurner97 Hi
> 请问你要更新客户端端口还是服务端的监听端口（35601）
> 还是网站前端的默认端口？

入站的前端默認端口

**Comment by CokeMine** [comment]
> > @LexBurner97 Hi
> > 请问你要更新客户端端口还是服务端的监听端口（35601）
> > 还是网站前端的默认端口？
> 
> 入站的前端默認端口，麻煩了大佬！

@LexBurner97 网站前端的端口？也就是说你使用的是Caddy？如果是这样的话进入/usr/local/caddy目录修改Caddyfile
然后执行service caddy restart重启caddy

**Comment by LexBurner97** [comment]
> > > @LexBurner97 Hi
> > > 请问你要更新客户端端口还是服务端的监听端口（35601）
> > > 还是网站前端的默认端口？
> > 
> > 
> > 入站的前端默認端口，麻煩了大佬！
> 
> @LexBurner97 网站前端的端口？也就是说你使用的是Caddy？如果是这样的话进入/usr/local/caddy目录修改Caddyfile
> 然后执行service caddy restart重启caddy

找到了！謝謝大佬！
