### ISSUE TITLE
需要修改caddy.service文件但是在/etc/systemd/system 无法找到

### ISSUE THREAD

**Issue by LexBurner97** [CokeMine/ServerStatus-Hotaru#34]
全程跟着步骤安装的探针，没有单独下载过caddy
因为需要加上cloudfalre的CDN因此下载了一个官方的插件来实现

curl https://getcaddy.com | bash -s personal tls.dns.cloudflare

但是需要修改当中的 caddy.service 中的环境变量才能实现
未能在一般情况下caddyservice存在的路径下找到，通过 find命令也没有搜索到在这个路径下有这个文件
求帮助，谢谢谢谢！

**Comment by CokeMine** [comment]
@LexBurner97 Hi,
因Caddy v1不再受支持，所以 https://getcaddy.com 也用不了了，这是官方的已编译tls.dns.cloudflare插件的Caddy V2版本二进制文件（Linux amd64架构）
`https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fcaddy-dns%2Fcloudflare`
配置请参考：https://github.com/caddy-dns/cloudflare
