### ISSUE TITLE
安装客户端之后启动失败

### ISSUE THREAD

**Issue by mitu752** [CokeMine/ServerStatus-Hotaru#36]
安装客户端之后启动失败
安装v2之后安装的

**Comment by mitu752** [comment]
![IMG_20200830_150352](https://user-images.githubusercontent.com/59833868/91653826-914f0f80-ead6-11ea-9ff3-c8809e427a3b.jpg)图

**Comment by CokeMine** [comment]
是什么系统，还有内核版本？

**Comment by mitu752** [comment]
debian 9  4.9内核

**Comment by mitu752** [comment]
我重装debian 9之后先装探针在装v2就成功了  也不知道什么原因

**Comment by CokeMine** [comment]
应该不是先安装v2的问题。。。具体原因也不好判断。
