### ISSUE TITLE
手机网页版增加负载显示

### ISSUE THREAD

**Issue by 110560** [CokeMine/ServerStatus-Hotaru#38]
手机网页版增加负载显示.....手机每次打开都必须调到电脑网页才能看到......
排版不够的话  可以稍微设置  网页可以稍微向右滑动一下。...
类似于另外一个修改版  那个逻辑  感谢。...

**Comment by 110560** [comment]
> 手机网页版增加负载显示.....手机每次打开都必须调到电脑网页才能看到......
> 排版不够的话 可以稍微设置 网页可以稍微向右滑动一下（手机网页可以左右滑动）。...
> 类似于另外一个修改版 那个逻辑 感谢。...

**Comment by CokeMine** [comment]
@110560 Hi,
注释掉
/usr/local/ServerStatus/web/css/main.css
两处
`	#load, tr td:nth-child(6) {
		display: none;
		visibility: hidden;
	}`
