### ISSUE TITLE
服务端经常莫名其妙的关闭

### ISSUE THREAD

**Issue by CirnoTH** [CokeMine/ServerStatus-Hotaru#39]
系统版本: Debian 10.5
使用的是最新的服务端版本，服务端经常莫名其妙的关闭。

**Comment by CokeMine** [comment]
会不会是内存不足被Kill了

**Comment by CirnoTH** [comment]
看了下，内存还剩不少，应该不是。关闭完全是随机的，我这被关闭很多次了

**Comment by CokeMine** [comment]
服务端的日志在/tmp/serverstatus_server.log 如果日志里服务端运行没有异常。
那就应该是服务端莫名其妙被Kill了

**Comment by CirnoTH** [comment]
又被关了，内存占用一直是正常的..
以下是日志全部内容
https://paste.ubuntu.com/p/Sb2rBFscBG/

**Comment by CokeMine** [comment]
日志上抛出报错的IP。是你的部分客户端IP吗

**Comment by CirnoTH** [comment]
绝大部分都不是，一堆不认识的国外ip

**Comment by CokeMine** [comment]
很奇怪，感觉像是被攻击爆破的感觉。
有没有尝试更换服务端的端口或换服务端
