### ISSUE TITLE
运行状态、CPU等全显示为维护中

### ISSUE THREAD

**Issue by ntgoaywh** [CokeMine/ServerStatus-Hotaru#41]
前几天我在服务端上删除两个节点信息后，打开网站发现节点信息全变红也就是全显示维护中，多次重启服务端和客户端，甚至重装了服务端和客户端再次添加节点后仍显示维护中

**Comment by CokeMine** [comment]
Hi,
如果方便的话，麻烦贴出/usr/local/ServerStatus/web/json/stats.json里面的内容

**Comment by ntgoaywh** [comment]
![image](https://user-images.githubusercontent.com/68455300/95188856-a3238100-07ff-11eb-9d07-70db0c133055.png)
这是截图

**Comment by CokeMine** [comment]
> ![image](https://user-images.githubusercontent.com/68455300/95188856-a3238100-07ff-11eb-9d07-70db0c133055.png)
> 这是截图
查看一下服务端的日志/tmp/serverstatus_server.log

**Comment by CokeMine** [comment]
> ![image](https://user-images.githubusercontent.com/68455300/95188856-a3238100-07ff-11eb-9d07-70db0c133055.png)
> 这是截图

查看一下服务端的日志/tmp/serverstatus_server.log

**Comment by ntgoaywh** [comment]
![image](https://user-images.githubusercontent.com/68455300/95189355-55f3df00-0800-11eb-96a7-b5cfe69f93e0.png)
![image](https://user-images.githubusercontent.com/68455300/95189382-5c825680-0800-11eb-9198-c1488401f27e.png)
这是日志

**Comment by CokeMine** [comment]
用这一服务端，别的客户端也有问题吗？

**Comment by ntgoaywh** [comment]
对的，我刚才又添加了一个节点，仍然显示为维护中
![image](https://user-images.githubusercontent.com/68455300/95190547-13330680-0802-11eb-8ae8-cb060ef0dbab.png)

**Comment by CokeMine** [comment]
如果你使用的腾讯云，是否有把入站端口安全组放开？
后台有个防火墙

**Comment by ntgoaywh** [comment]
几天前我所有的服务器都是显示正常的，我删除了两个节点之后，进入网站后就发现所有节点信息全显示为维护中。

**Comment by CokeMine** [comment]
客户端用脚本关闭一下
然后python /usr/local/ServerStatus/client/status-client.py看看是什么报错

**Comment by ntgoaywh** [comment]
emm我不太懂python，是要这样吗，一直无法连接
![image](https://user-images.githubusercontent.com/68455300/95195569-517ff400-0809-11eb-95ad-3fd1a6db840b.png)
![image](https://user-images.githubusercontent.com/68455300/95195722-8e4beb00-0809-11eb-9519-acb3a3c3e9d7.png)

**Comment by CokeMine** [comment]
如果用域名当作客户端地址的话，有没有加Cloudflare等CDN？

**Comment by ntgoaywh** [comment]
总算可以了！！我前几天把cf代理打开了，刚刚关了就好了！非常感谢！

**Comment by CokeMine** [comment]
客户端填服务端地址的时候就填IP吧，
前端同时还可以用域名加CDN
