### ISSUE TITLE
编译vnStat失败，请手动安装vnStat

### ISSUE THREAD

**Issue by nauya** [CokeMine/ServerStatus-Hotaru#43]
编译vnStat失败，请手动安装vnStat
出现这种情况，不知道是什么原因。

**Comment by CokeMine** [comment]
谢谢反馈，请问是什么系统，及系统版本

**Comment by nauya** [comment]
centos 7   7.2到7。7貌似都不行

**Comment by nauya** [comment]
编译vnStat失败，请手动安装vnStat
[root@VM-0-4-centos ~]# cd vnstat-*/
[root@VM-0-4-centos vnstat-2.6]# ./configure --prefix=/usr --sysconfdir=/etc && make
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking for pow in -lm... yes
checking for sqlite3_prepare_v2 in -lsqlite3... yes
checking for gdImagePng in -lgd... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CHECK... no
configure: testcases can not be execute without check installed
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/root/vnstat-2.6':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
[root@VM-0-4-centos vnstat-2.6]#

**Comment by nauya** [comment]
还有个问题，我的系统是
[root@VM-0-4-centos ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core) 
但是貌似安装程序时会提示
[信息] 检测到你的系统为 CentOS6，该系统自带的 Python2.6 版本过低，会导致无法运行客户端，如果你有能力升级为 Python2.7或以上版本，那么请继续(否则建议更换系统)：[y/N]

**Comment by CokeMine** [comment]
```
yum -y groupinstall "Development Tools"
```
看看能配置好编译环境吗

**Comment by nauya** [comment]
我试了一台可以，我吧我所有的都重装一遍试试。应该没啥问题了 挺顺利的

**Comment by xxyyyx** [comment]
> ```
> yum -y groupinstall "Development Tools"
> ```
> 
> 看看能配置好编译环境吗

ubuntu 20.04也出现这个问题应该咋整啊
