### ISSUE TITLE
ARM64的处理器无法安装Caddy

### ISSUE THREAD

**Issue by rhwong** [CokeMine/ServerStatus-Hotaru#50]
在AWS上新开了个c4g时发现的，处理器类型显示为[aarch64]，实际上就是ARM64，
对应https://github.com/caddyserver/caddy/releases/download/v1.0.4/caddy_v1.0.4_linux_arm64.tar.gz
我看您代码里把解压步骤省略，指向了已经解压好的仓库，所以就不fork了

**Comment by CokeMine** [comment]
这样应该可以了

**Comment by rhwong** [comment]
谢谢~
