### ISSUE TITLE
是否考虑支持下docker？

### ISSUE THREAD

**Issue by JunzhouLiu** [cokemine/ServerStatus-Hotaru#52]
使用docker-compose快速拉起服务端（包括前端），以及拉起（心跳客户端）无论是从环境隔离上还是快速部署上考虑都是比较好的解决方案。

**Comment by JunzhouLiu** [comment]
还一个问题，在国内阿里云的服务器上执行快速安装脚本会失败以及中断，因为阿里云服务器经常不能访问（此问题可以通过修改DNS以及采用代理解决）https://raw.githubusercontent.com/，如果有条件，快速安装脚本中可以在拉取https://raw.githubusercontent.com/失败时转为拉取cdn上的文件。（或者安装前尝试访问https://raw.githubusercontent.com/，无法访问则后续拉取资源从cdn上拉取）。

**Comment by JunzhouLiu** [comment]
![image](https://user-images.githubusercontent.com/17582066/102178387-48359680-3ee0-11eb-88b6-4b4921deaa46.png)

这个黑色的字体和背景图片搭配会导致视觉上看不清楚。

**Comment by CokeMine** [comment]
中国大陆地区访问GitHub不稳定有一段时间了，目前没有建一个镜像或使用Gitee专为中国大陆地区的服务器提供下载的计划。。关于这个前端，已经被我改的我自己都看不懂是啥了，以后想的是换个框架重写一下。

**Comment by fmbfmbhh** [comment]
同支持，是否有大佬能做个镜像，非常喜欢这个项目希望能在openwrt上使用，感谢

**Comment by imbytecat** [comment]
> 同支持，是否有大佬能做个镜像，非常喜欢这个项目希望能在openwrt上使用，感谢

我做了一个 Docker 镜像，并持续更新，目前支持 `amd64` 和 `arm64v8`，可以用以下命令安装：

```bash
docker run -d --restart=always --name serverstatus -p 8080:8080 -p 35601:35601 -v /srv/serverstatus/config.json:/opt/config.json imbytecat/serverstatus
```

更多细节请前往 [Docker Hub](https://hub.docker.com/repository/docker/imbytecat/serverstatus/general)
