### ISSUE TITLE
全新搭建服务端及客户端仅显示维护中

### ISSUE THREAD

**Issue by trojson** [CokeMine/ServerStatus-Hotaru#54]
嗨 CokeMine 按照你的分享资源搭建好服务端 客户端配置好都是一直显示 维护中，试过 CentOS 7 以及 Debian 9 都是一样情况，网页是可以直接登录，安装的时候无论是 域名 还是 IP 都是一样无法获取客户端信息，是否跟 系统自带 Python 版本有关？VPS 是重装系统后全新的。

**Comment by CokeMine** [comment]
是不是服务端的服务器的安全组没有打开？

**Comment by trojson** [comment]
VPS没有开防火墙端口应该没被卡

**Comment by CokeMine** [comment]
客户端先```bash status.sh c``` 停止 客户端，然后```python /usr/local/ServerStatus/client/status-client.py``` 看看是什么错误

**Comment by trojson** [comment]
一直循环
Connecting...
Disconnected...

**Comment by CokeMine** [comment]
那应该还是服务端安全组或防火墙的问题。

**Comment by trojson** [comment]
搞好了 一些细节没看清楚 操作太快 Lol 感谢指导，已加TG群 ！

**Comment by AndersonGhost** [comment]
> 那应该还是服务端安全组或防火墙的问题。

与楼主一样的现象：全新搭建服务端及客户端仅显示维护中
客户端先bash status.sh c 停止 客户端，然后python /usr/local/ServerStatus/client/status-client.py 然后显示：
一直循环
Connecting...
Disconnected...

我使用的是甲骨文云，防火墙也都关闭了，目前还是显示“维护中”，现在该如何处理？

**Comment by trojson** [comment]
> > 那应该还是服务端安全组或防火墙的问题。
> 
> 与楼主一样的现象：全新搭建服务端及客户端仅显示维护中
> 客户端先bash status.sh c 停止 客户端，然后python /usr/local/ServerStatus/client/status-client.py 然后显示：
> 一直循环
> Connecting...
> Disconnected...
> 
> 我使用的是甲骨文云，防火墙也都关闭了，目前还是显示“维护中”，现在该如何处理？

我的情况是 客户端第一次配置的 服务端的 （第一项）地址搞反了，应该填写的是服务端地址不是本机地址，具体得自己重新检查下配置是否正确。

**Comment by AndersonGhost** [comment]
> > > 那应该还是服务端安全组或防火墙的问题。
> > 
> > 
> > 与楼主一样的现象：全新搭建服务端及客户端仅显示维护中
> > 客户端先bash status.sh c 停止 客户端，然后python /usr/local/ServerStatus/client/status-client.py 然后显示：
> > 一直循环
> > Connecting...
> > Disconnected...
> > 我使用的是甲骨文云，防火墙也都关闭了，目前还是显示“维护中”，现在该如何处理？
> 
> 我的情况是 客户端第一次配置的 服务端的 （第一项）地址搞反了，应该填写的是服务端地址不是本机地址，具体得自己重新检查下配置是否正确。

好的，谢谢~~
