### ISSUE TITLE
还是老毛病,纯ipv6服务器一直显示维护中

### ISSUE THREAD

**Issue by GhostHjh** [CokeMine/ServerStatus-Hotaru#63]
主服务器为俄罗斯服务器,系统为Debain10 x64,
纯ipv6服务器为德国服务器系统为centos7 x64,
ipv6服务器客户端填主服务器的ipv6地址,但是指针依旧显示ipv6服务器为维护中,主服务器的状态为正常状态,
[之前搞好过一次](https://github.com/CokeMine/ServerStatus-Hotaru/issues/42),但是这次我用上一次的方法却不行了,是以为系统不一样吗?
顺便弱弱的问一句.......可以支持https吗?

**Comment by GhostHjh** [comment]
这个是我的探针: [http://cszdllk.ml]

**Comment by GhostHjh** [comment]
顺便: 新年快乐

**Comment by CokeMine** [comment]
新年快乐！
用脚本关闭客户端，手动运行一下看看报什么错？
```
python /usr/local/ServerStatus/client/status-client.py

**Comment by GhostHjh** [comment]
ipv6服务器报错显示为:
```
Connecting...
Disconnected...
```
循环显示

**Comment by GhostHjh** [comment]
最新情况,好像在运行了一个[bbr加速四合一脚本](https://github.com/chiakge/Linux-NetSpeed)中的系统优化后可以被使用了,但是我没有进行详细的测试,不够也许可以做为一个解决方案被使用.

他的优化选项为:
```
net.ipv6.conf.default.autoconf = 0
net.ipv6.conf.default.accept_ra = 0
net.ipv6.conf.all.autoconf = 0
net.ipv6.conf.all.accept_ra = 0
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = nanqinlang
fs.file-max = 1000000
fs.inotify.max_user_instances = 8192
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 1024 65000
net.ipv4.tcp_max_syn_backlog = 16384
net.ipv4.tcp_max_tw_buckets = 6000
net.ipv4.route.gc_timeout = 100
net.ipv4.tcp_syn_retries = 1
net.ipv4.tcp_synack_retries = 1
net.core.somaxconn = 32768
net.core.netdev_max_backlog = 32768
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_max_orphans = 32768
net.ipv4.ip_forward = 1
```

这大概就是传说中的:
![为什么可以运行了?](https://www.helloimg.com/images/2021/02/12/whyd242e2bdcdaf2a1d.png)

**Comment by CokeMine** [comment]
```
net.ipv6.conf.default.autoconf = 0
net.ipv6.conf.default.accept_ra = 0
net.ipv6.conf.all.autoconf = 0
net.ipv6.conf.all.accept_ra = 0
```

应该是取消了IPv6的autoconf，使用static ipv6，应该是因为autoconf监听不到吧
至于使用ssl，只需要修改/usr/local/caddy/Caddyfile，按照Caddy配置ssl添加就行，然后

```
service caddy restart
```

**Comment by GhostHjh** [comment]
我是试着在Caddy配置中添加了
```
tls 证书文件 密钥文件
```
并更改了
```
http://域名:80{
..............................
}
```
为
```
域名{
....................
}
```
但是.......现在网站访问的时候是一片空白的,
虽然已经显示https证书为有效的,
但是,即使我将Caddyfiile改回原来的样子,也会发现重启Caddy会启动失败.现在就是.......骑虎难下

**Comment by GhostHjh** [comment]
搞好了.....虽然我也不知道为什么搞好了......但是它就是可以运行了
