### ISSUE TITLE
大佬，想提个需求，能不能用IP地址自动判断小鸡区域/国家 

### ISSUE THREAD

**Issue by Anaple** [CokeMine/ServerStatus-Hotaru#65]
客户端能不能实现调用IP库自动获取小鸡国家/地区发给服务端，还有通过类似virt-what的东西自动判断虚拟化类型，不用自己手动在服务端输入。

**Comment by CokeMine** [comment]
如果要改成在客户端获取这些数据，那么服务端也必须要修改。
这样所有已安装客户端的也得更新版本。
通过IP库自动判定VPS的地区不一定准确。
因为对于一个VPS的地区和虚拟化一般来说不会改变，所以还是指定在服务端比较好，也避免客户端向服务端过多的传输数据消耗流量。

**Comment by Anaple** [comment]
好的，我尝试用Java重构一遍服务端，再添加一个前端面板可用于在直接在前端添加VPS，现在的这个添加方式确实有点不方便。
