### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by Naruse-Developer** [CokeMine/ServerStatus-Hotaru#7]
//serverstatus_tw.js
TableRow.children["memory"].children[0].children[0].className = "progress-bar progress-bar-warning"; // 此处没有效果

似乎显示的css是
progress-bar {
    background: linear-gradient(to right, #44ce78 0%,#43ce9f 100%)!important; //main.css - 3785
}

.progress-bar-warning {
  background-color: #f0ad4e; //Coce.css - 5758 ，虽然有定义，但是无法显示效果
}

**Comment by CokeMine** [comment]
确实所有的资源≥80%的warning都没效果。
修复了。
