### ISSUE TITLE
发现一个问题,使用Vnstat客户端后,流量就不变化了

### ISSUE THREAD

**Issue by jth445600** [CokeMine/ServerStatus-Hotaru#74]
我用博客里的脚本安装的服务端和客户端.
不是说里边有vnstat吗?
机器重启后,流量就归零了.

**Comment by jth445600** [comment]
发现一个问题,使用Vnstat客户端后,流量就不变化了.
在几台vps上安装测试后发现.
如果使用vnstat客户端,流量会固定在安装时.
看样子VNstat不会更新流量变化.

**Comment by jth445600** [comment]
我猜测是因为,之前从YUM仓库中安装过vnstat,虽然后来卸载了,但是安装vnstat客户端后,仍旧会调用某个旧文件的流量记录.

**Comment by CokeMine** [comment]
vnStat默认是5分钟更新一次数据库，是很长时间流量记录都没有变吗

**Comment by cheneyxx** [comment]
> vnStat默认是5分钟更新一次数据库，是很长时间流量记录都没有变吗

如何卸载vnStat

**Comment by CokeMine** [comment]
> > vnStat默认是5分钟更新一次数据库，是很长时间流量记录都没有变吗
> 
> 如何卸载vnStat

脚本是直接编译安装vnStat的，一般是没有必要卸载的因为可以重新配置客户端使用原本的流量计算即可。如果需要卸载就在源代码目录下`make uninstall`

**Comment by jth445600** [comment]
流量值一直不变

**Comment by GloryBoy239** [comment]
我也是这问题，通过手动编译安装了一遍，还是不行。
但是，通过：vnstat -h    #按小时查询
vnstat -d    #按天数查询
vnstat -m    #按月数查询
vnstat -w    #按周数查询

这些命令，又能查看到相关流量信息。

直观感觉好像是：Vnstat安装成功，但是和服务端之间好像没有联系。所以服务端显示的仍是开机后的流量

**Comment by jth445600** [comment]
@GloryBoy239 你用的什么系统，我用的centos7

**Comment by GloryBoy239** [comment]
debian9

jth445600 ***@***.***> 于 2021年4月22日周四 17:01写道：

**Comment by CokeMine** [comment]
@GloryBoy239 Shell脚本会通过选项修改客户端执行逻辑的，尝试运行脚本执行0更新一下，然后更新一下客户端，再重新配置一下看看
@jth445600 你那边执行`vnstat -m`的数据是正常的吗

**Comment by jth445600** [comment]
搞定了

**Comment by GloryBoy239** [comment]
> @GloryBoy239 Shell脚本会通过选项修改客户端执行逻辑的，尝试运行脚本执行0更新一下，然后更新一下客户端，再重新配置一下看看
> @jth445600 你那边执行`vnstat -m`的数据是正常的吗

OK了，谢谢大佬

**Comment by jth445600** [comment]
又来了. debian9系统,装的vnstat客户端.重启之后流量清零.但是`vnstat -m`是有数据的
![image.png](https://i.loli.net/2021/04/28/z1C7yuoPZnYXGp6.png)
![image.png](https://i.loli.net/2021/04/28/fO5P4ZcAIQrzkHC.png)

**Comment by CokeMine** [comment]
更新一下脚本，然后更新一下客户端重新配置一下吧。

Toyo留下的脚本很多地方实在是太冗余了，Shell又没有办法进行很好的单元测试，一些地方只能我自己本地测试。。
