### ISSUE TITLE
想改网页内的几个字 如何操作

### ISSUE THREAD

**Issue by only4freedom** [cokemine/ServerStatus-Hotaru#75]
今天没事更新了下发现index内容变了..,
我想改Server Status
Servers' Probes Set up with ServerStatus这段话 该如何操作呢.

**Comment by CokeMine** [comment]
1、安装Node.js Git
2、`git clone https://github.com/CokeMine/Hotaru_theme.git`
3、`cd ./Hotaru_theme && npm install`
4、修改 
https://github.com/CokeMine/Hotaru_theme/blob/dev/src/components/TheHeader.vue#L7
5、`npm run build`
6、复制`dist`目录到服务器

**Comment by annkoxx** [comment]
> 1、安装Node.js Git
> 2、`git clone https://github.com/CokeMine/Hotaru_theme.git`
> 3、`cd ./Hotaru_theme && npm install`
> 4、修改
> https://github.com/CokeMine/Hotaru_theme/blob/dev/src/components/TheHeader.vue#L7
> 5、`npm run build`
> 6、复制`dist`目录到服务器

不能直接从服务器上面改目标文件吗

**Comment by cokemine** [comment]
> > 1、安装Node.js Git
> > 2、`git clone https://github.com/CokeMine/Hotaru_theme.git`
> > 3、`cd ./Hotaru_theme && npm install`
> > 4、修改
> > https://github.com/CokeMine/Hotaru_theme/blob/dev/src/components/TheHeader.vue#L7
> > 5、`npm run build`
> > 6、复制`dist`目录到服务器
> 
> 不能直接从服务器上面改目标文件吗

如果你能找到这个字符串在哪里的话可以这么做
