### ISSUE TITLE
请求增加欧盟图标

### ISSUE THREAD

**Issue by KevinZonda** [cokemine/ServerStatus-Hotaru#79]
![image](https://user-images.githubusercontent.com/33132228/119360175-413a5d80-bca2-11eb-85b5-35f9c341a8a4.png)

**Comment by CokeMine** [comment]
EU是不在ISO 3166-1标准里的.....主要是我找不到这一套图标的最初出处，如果这一套图标有EU图标的话也是可以加进去的

**Comment by cokemine** [comment]
Emmm...我才发现原来这套图标是Twitter的 https://github.com/twitter/twemoji
我这边已经找好轮子过段时间转换一下，多加一些旗帜。并把所有图标转换成SVG格式的

**Comment by cokemine** [comment]
Done in https://github.com/cokemine/Hotaru_theme/commit/6ae6becc7b8b924b49ccebda1961cb60c9df5c35
