### ISSUE TITLE
手动安装出错：Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by AdiEcho** [CokeMine/ServerStatus-Hotaru#8]
同样的环境下逗比大佬的就能正常使用，出错在`./sergate`这一步，这在好几台服务器上都得到了验证。

> root@10-9-69-132:/home/ubuntu/ServerStatus-Toyo/server# ./sergate
> [server]: Bound to :35601
> ^C[EXIT] Caught signal 2
> [server]: Closing.
> root@10-9-69-132:/home/ubuntu/ServerStatus-Toyo/server# cd /home/ubuntu/ServerStatus-Toyo/ServerStatus-Hotaru/server
> root@10-9-69-132:/home/ubuntu/ServerStatus-Toyo/ServerStatus-Hotaru/server# ./sergate
> [server]: Bound to :35601
> Segmentation fault (core dumped)

网上搜原因后自感无力解决，只好求助大佬

**Comment by CokeMine** [comment]
修改config.json
你康康是不是没有加region

**Comment by AdiEcho** [comment]
@CokeMine 已经加了，但是还是会报错，不过现在直接用一键的了。没看代码前以为会自动安装Caddy，发现可以不安装后就用脚本了。
