### ISSUE TITLE
ssl如何添加

### ISSUE THREAD

**Issue by annkoxx** [cokemine/ServerStatus-Hotaru#93]
ssl如何添加

https://xxxxxxxxxxxxxx:80 {
 root * /usr/local/ServerStatus/web
 encode gzip
 file_server
 tls /usr/local/caddy/zs.pem /usr/local/caddy/miyao.key
}

/usr/local/caddy/Caddyfile 目录的 这样是不行的

**Comment by cokemine** [comment]
https和80端口显然是冲突的，建议参考网络上Caddy配置ssl的文章或官方文档
