### ISSUE TITLE
ubuntu 20.04.2 LTS 安装客户端出现 ('Caught Exception:', IndexError('list index out of range',))

### ISSUE THREAD

**Issue by wmjlxl** [cokemine/ServerStatus-Hotaru#94]
ubuntu 20.04.2 LTS 安装客户端出现 ('Caught Exception:', IndexError('list index out of range',))

You are connecting via: IPv4

('Caught Exception:', IndexError('list index out of range',))
Connecting...
Authentication successful. Access granted.

....

不停重复。

尝试过删除，reboot，重新安装。都是一个情况。
请问这个该如何解决？谢谢。

**Comment by cokemine** [comment]
Emmm...Python版本的确实会出现各种各样奇怪的问题。我怀疑是脚本把客户端的配置写乱了。
可以看看`cat /usr/local/ServerStatus/client/status-client.py` 
不过你可以先用一下这个
https://github.com/cokemine/ServerStatus-goclient
效率应该也比Python版本的高

**Comment by wmjlxl** [comment]
go version 没问题。非常感觉。

**Comment by cokemine** [comment]
`list index out of range`我知道原因了,应该是vnStat刚安装还没有开始收集数据会导致错误,应该安装vnStat 5分钟左右后就可以正常工作了.
