### ISSUE TITLE
同一服务器安装了宝塔。怎么才能把探针安装到另外一个端口让正常运行。

### ISSUE THREAD

**Issue by annkoxx** [cokemine/ServerStatus-Hotaru#95]
同一服务器安装了宝塔。怎么才能把探针安装到另外一个端口让正常运行。

服务器先安装了探针，正常运行。
最后安装了宝塔，
然后探针访问显示没绑定
没有找到站点
您的请求在Web服务器中没有找到对应的站点！

问一下如果要共存应该怎样设置探针端口

**Comment by heaid** [comment]
压根也不冲突阿 你自己宝塔面板开放端口  可以用个域名反代。我就是一个服务器   装了 宝塔   探针   博客   网盘  科学上网 。这些都不冲突

**Comment by annkoxx** [comment]
> 压根也不冲突阿 你自己宝塔面板开放端口 可以用个域名反代。我就是一个服务器 装了 宝塔 探针 博客 网盘 科学上网 。这些都不冲突

关键是我先前先把探针安装了80端口。然后在宝塔的时候忘记了，也是建站是80端口。已经建出来了的探针怎么更改端口。

**Comment by cokemine** [comment]
> > 压根也不冲突阿 你自己宝塔面板开放端口 可以用个域名反代。我就是一个服务器 装了 宝塔 探针 博客 网盘 科学上网 。这些都不冲突
> 
> 关键是我先前先把探针安装了80端口。然后在宝塔的时候忘记了，也是建站是80端口。已经建出来了的探针怎么更改端口。

把Caddy卸载掉。用宝塔的Nginx作服务器
```
wget https://raw.githubusercontent.com/cokemine/ServerStatus-Hotaru/master/caddy/caddy_install.sh
bash caddy_install.sh uninstall
```

**Comment by annkoxx** [comment]
> > > 压根也不冲突阿 你自己宝塔面板开放端口 可以用个域名反代。我就是一个服务器 装了 宝塔 探针 博客 网盘 科学上网 。这些都不冲突
> > 
> > 
> > 关键是我先前先把探针安装了80端口。然后在宝塔的时候忘记了，也是建站是80端口。已经建出来了的探针怎么更改端口。
> 
> 把Caddy卸载掉。用宝塔的Nginx作服务器
> 
> ```
> wget https://raw.githubusercontent.com/cokemine/ServerStatus-Hotaru/master/caddy/caddy_install.sh
> bash caddy_install.sh uninstall
> ```

那之前建的那些探针数据是不是就没了

**Comment by annkoxx** [comment]
> > > > 压根也不冲突阿 你自己宝塔面板开放端口 可以用个域名反代。我就是一个服务器 装了 宝塔 探针 博客 网盘 科学上网 。这些都不冲突
> > > 
> > > 
> > > 关键是我先前先把探针安装了80端口。然后在宝塔的时候忘记了，也是建站是80端口。已经建出来了的探针怎么更改端口。
> > 
> > 
> > 把Caddy卸载掉。用宝塔的Nginx作服务器
> > ```
> > wget https://raw.githubusercontent.com/cokemine/ServerStatus-Hotaru/master/caddy/caddy_install.sh
> > bash caddy_install.sh uninstall
> > ```
> 
> 那之前建的那些探针数据是不是就没了

现在东西都还在，都在转。就是端口问题解决不了

**Comment by cokemine** [comment]
> > > > > 压根也不冲突阿 你自己宝塔面板开放端口 可以用个域名反代。我就是一个服务器 装了 宝塔 探针 博客 网盘 科学上网 。这些都不冲突
> > > > 
> > > > 
> > > > 关键是我先前先把探针安装了80端口。然后在宝塔的时候忘记了，也是建站是80端口。已经建出来了的探针怎么更改端口。
> > > 
> > > 
> > > 把Caddy卸载掉。用宝塔的Nginx作服务器
> > > ```
> > > wget https://raw.githubusercontent.com/cokemine/ServerStatus-Hotaru/master/caddy/caddy_install.sh
> > > bash caddy_install.sh uninstall
> > > ```
> > 
> > 
> > 那之前建的那些探针数据是不是就没了
> 
> 现在东西都还在，都在转。就是端口问题解决不了

把Caddy卸载掉，在宝塔新建个站点，目录指向/usr/local/ServerStatus/web，由于宝塔的限制可能需要手动编辑站点目录。之后的你就不用管了，可以正常跑

**Comment by heaid** [comment]
/usr/local/ServerStatus/   这个里面有设置端口的文件和你配置的数据。自己备份一下就行

**Comment by annkoxx** [comment]
> > > > > > 压根也不冲突阿 你自己宝塔面板开放端口 可以用个域名反代。我就是一个服务器 装了 宝塔 探针 博客 网盘 科学上网 。这些都不冲突
> > > > > 
> > > > > 
> > > > > 关键是我先前先把探针安装了80端口。然后在宝塔的时候忘记了，也是建站是80端口。已经建出来了的探针怎么更改端口。
> > > > 
> > > > 
> > > > 把Caddy卸载掉。用宝塔的Nginx作服务器
> > > > ```
> > > > wget https://raw.githubusercontent.com/cokemine/ServerStatus-Hotaru/master/caddy/caddy_install.sh
> > > > bash caddy_install.sh uninstall
> > > > ```
> > > 
> > > 
> > > 那之前建的那些探针数据是不是就没了
> > 
> > 
> > 现在东西都还在，都在转。就是端口问题解决不了
> 
> 把Caddy卸载掉，在宝塔新建个站点，目录指向/usr/local/ServerStatus/web，由于宝塔的限制可能需要手动编辑站点目录。之后的你就不用管了，可以正常跑

谢谢，解决了

**Comment by annkoxx** [comment]
> > > > > > 壓根沒有衝突阿你寶塔開放端口可以用一個市場反代代。我就是一個服務器裝了寶塔自己的博客網盤科學上網。
> > > > > 
> > > > > 
> > > > > 關鍵是我之前先把安裝了80端口。然後在寶的時候忘記了，也是建站是80端口。
> > > > 
> > > > 
> > > > 把Caddy卸掉。用寶塔的Nginx作服務器
> > > > ```
> > > > wget https://raw.githubusercontent.com/cokemine/ServerStatus-Hotaru/master/caddy/caddy_install.sh
> > > > bash caddy_install.sh uninstall
> > > > ```
> > > 
> > > 
> > > 那之前建的那些數據是不是了
> > 
> > 
> > 現在東西都還在，都在轉。就是端口問題解決不了
> 
> 把Caddy卸掉，在寶塔新建一個站點，目錄菜單/usr/local/ServerStatus/web，因為寶塔的限制可能需要手動編輯站點目錄。之後的就不用管了，你可以正常跑

如果我迁移的话，直接把/usr/local/ServerStatus/web目录下所有东西，挪到另外一个服务器同目录下  可以吗？
